.TH spotify-dj 1 "@DATE@" "spotify-dj @VERSION@" "spotify-dj manual"

.SH NAME
spotify-dj \- A remote controlled DJ for Spotify

.SH SYNOPSIS
.B spotify-dj
[OPTIONS]

.SH AUTHOR
Written by Mantas Norvaisa.

.SH REPORTING BUGS
Report bugs to <mntnorv+bugs at gmail dot com> or create an issue in Github at
<https://www.github.com/mntnorv/spotify-dj>.
