.TH spotd 1 "@DATE@" "spotd @VERSION@" "spotd manual"

.SH NAME
spotd \- A daemon for playing music from Spotify

.SH SYNOPSIS
.B spotd
[OPTIONS]

.SH AUTHOR
Written by Mantas Norvaisa.

.SH REPORTING BUGS
Report bugs to <mntnorv+bugs at gmail dot com> or create an issue in Github at
<https://www.github.com/mntnorv/spotd>.
